apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mirror-api
  template:
    metadata:
      labels:
        app: mirror-api
    spec:
      containers:
        - name: mirror-api
          image: nonbreakingspace/mirror-api:latest
          ports:
            - containerPort: 4000
          args: ["foreground"]
          env:
            - name: DB_HOST
              value: "***DB_HOST***"
            - name: USERNAME
              value: "admin"
            - name: PASSWORD
              value: "***DB_PASSWORD***"
            - name: DATABASE
              value: "mirror_new_prod"
            - name: SECRET_KEY_BASE
              value: "***SECRET_KEY_BASE***"
      imagePullSecrets:
      - name: regcred