apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mirror
      tier: backend
  template:
    metadata:
      labels:
        app: mirror
        tier: backend
    spec:
      containers:
        - name: mirror
          image: nonbreakingspace/mirror-api:latest
          ports:
            - name: http
              containerPort: 4000
          args: ["foreground"]
          env:
            - name: DB_HOST
              value: "***DB_HOST***"
            - name: USERNAME
              value: "admin"
            - name: PASSWORD
              value: "***DB_PASSWORD***"
            - name: DATABASE
              value: "mirror_new_prod"
            - name: SECRET_KEY_BASE
              value: "***SECRET_KEY_BASE***"
          # livenessProbe:
          #   httpGet:
          #     path: /api/kube_health
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
      imagePullSecrets:
      - name: regcred