apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mirror
      tier: backend
  template:
    metadata:
      labels:
        app: mirror
        tier: backend
    spec:
      containers:
        - name: mirror
          image: nonbreakingspace/mirror-api:latest
          ports:
            - name: http
              containerPort: 4000
          args: ["foreground"]
          env:
            - name: HOST
              value: "//157.230.64.249"
            - name: DB_HOST
              value: "68.183.98.121"
            - name: USERNAME
              value: "admin"
            - name: PASSWORD
              value: "35764652727ab62770b9295cfb80f2bfd5fbec0bb0303efa"
            - name: DATABASE
              value: "mirror_new_prod"
            - name: SECRET_KEY_BASE
              value: "PaiowhrbZBKyE5NxFlvy1tpJ03BvK9jS9IHhoOXfxQ7wbU7VX/cDJLJbPlnjtVeK"
          livenessProbe:
            httpGet:
              path: /api/kube_health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
      imagePullSecrets:
      - name: regcred