apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mirror-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - usemirror.io
    secretName: letsencrypt-prod
  rules:
  - host: usemirror.io
    http:
      paths:
      - backend:
          serviceName: mirror-frontend
          servicePort: 80