{application,phoenix_ecto,
             [{registered,[]},
              {description,"Integration between Phoenix & Ecto"},
              {vsn,"3.0.1"},
              {modules,['Elixir.Phoenix.Ecto',
                        'Elixir.Phoenix.Ecto.SQL.Sandbox',
                        'Elixir.Plug.Exception.Ecto.CastError',
                        'Elixir.Plug.Exception.Ecto.NoResultsError',
                        'Elixir.Plug.Exception.Ecto.Query.CastError']},
              {applications,[kernel,stdlib,elixir,logger,ecto,plug]}]}.