# # ./docker-compose.yml

# web:
#   build: .
#   dockerfile: Dockerfile # That's our Dockerfile path
#   command: mix phoenix.server # Start the server if no other command is specified
#   environment:
#     - MIX_ENV=prod # That's the environment mode, you know
#     - PORT=4000
#   volumes:
#     - .:/app # Here we're mounting our project's root directory inside the container
#   ports:
#     - "4000:4000"
#   links:
#     - mysql

# mysql:
#   image: mysql:latest # https://hub.docker.com/_/postgres/
#   environment:
#    - MYSQL_ROOT_PASSWORD=gia123
#   ports:
#     - "3306:3306"

version: '2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "gia123"
  app:
    build: .
    command: mix phoenix.server
    # depends_on:
    #   - db
    volumes:
      - .:/app
    # links:
    #   - db
    ports:
      - 4000:4000
    environment:
      MIX_ENV: prod